### ISSUE TITLE
Fix flaky spec in vacation_mailer_spec

### ISSUE THREAD

**Issue by thiagofportella** [Codeminer42/Punchclock#505]
Log:
```
Failures:

  1) VacationMailer vacation email when a vacation is cancelled by the user renders the receivers emails
     Failure/Error: expect(mail.to).to eq(vacation_managers.map(&:email))

       expected: ["darrick@klein-wolf.org", "minda_hackett@ritchie-kessler.name"]
            got: ["minda_hackett@ritchie-kessler.name", "darrick@klein-wolf.org"]

       (compared using ==)
     # ./spec/mailers/vacation_mailer_spec.rb:165:in `block (4 levels) in <top (required)>'
```
